### ISSUE TITLE
Guest User Access

### ISSUE THREAD

**Issue by mrefaat** [salesforce-experiencecloud/MultiLevelNavigationMenu#1]
The menu is not showing for Guest User.

I've done the following but it s still not working 

- Gave access to menu objects for guest users 
- Defined menu items as public

**Comment by gtabboud** [comment]
Please review the "Sharing, Access, and Security Requirements" section in this doc: https://salesforce.quip.com/4EMxAD8a2uEn

**Comment by mrefaat** [comment]
Thanks for your reply. I've done all of this
i found this error in the console 
lwr_app:1 TypeError: Cannot read properties of undefined (reading 'length')
    at get menuAriaAnnouncement (modules/ccnavmenus/navMenu.js:1:9265)
    at _.hybridGetTrap [as get] (eval at Xp (lwr_bootstrap_locker:25:156), <anonymous>:5:6965)
    at D (modules/ccnavmenus/navMenu.js:1:4998)
    at eval (eval at Xp (lwr_bootstrap_locker:25:156), <anonymous>:5:11189)
    at lwr_bootstrap_locker:23:2794
    at _.apply (lwr_bootstrap_locker:23:4383)
    at lwr_lwc:7:2538
    at _t.observe (lwr_lwc:1:7416)
    at an (lwr_lwc:7:2140)
    at G (lwr_lwc:7:7313)

**Comment by mrefaat** [comment]
Yes it's working now thanks a lot
